In [150]:
import pandas as pd

In [151]:
import numpy as np

In [152]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [153]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [154]:
#Q1. Pandas version

pd.__version__

'3.0.6'

In [155]:
#Q2.  Records  Count
len(df)

10000

In [156]:
#Q3. Fuel Types
df["fuel_type"].nunique()

3

In [157]:
#Q4.Missing Values
li=df.isna().any()

li.sum()

np.int64(2)

In [158]:
#Q5. Max Fuel Efficiency
df["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [159]:
#Q6. Median Value Of Horsepower
med = df["horsepower"].median()
med

np.float64(254.0)

In [160]:
freq = df["horsepower"].mode()[0]
freq

np.float64(252.0)

In [161]:
df["horsepower"].fillna(freq)

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [164]:
df["horsepower"].median()

np.float64(254.0)

In [165]:
## The median didnt change,  previously, 254, after fillna(freq), still 254

In [186]:
groups =  df.groupby("origin")

In [189]:
asia =  groups.get_group("Asia")
asia

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [191]:
nd=df[["model_year","vehicle_weight"]]
nd

      model_year  vehicle_weight
0           2006            3870
1           2008            4210
2           1996            4240
3           1989            4490
4           1994            4510
...          ...             ...
9995        2005            4690
9996        1993            4370
9997        2014            4590
9998        2004            4450
9999        2011            4370

[10000 rows x 2 columns]